on:
  schedule:
    - cron: '53 20,8 * * *'
  push:
    branches:
      - master

jobs:
  update:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - run: pip install -r src/tool/requirements.txt && python -m src.tool.version_updater
      - run: rm -rf res/ && mkdir -p res/ && mkdir -p tmp/
      - uses: actions/checkout@v4
        with:
          repository: Kengxxiao/ArknightsGameData
          path: tmp/
          sparse-checkout: zh_CN/gamedata/excel/
      - run: mv tmp/zh_CN/gamedata/excel/ res/ && rm -rf tmp/
      - run: git config --local user.name 'github-actions[bot]' && git config --local user.email 'github-actions[bot]@users.noreply.github.com'
      - run: git add . && git commit -m 'automatic update' && git push origin master || true
